inventory:
  plugin: SimpleInventory
  options:
    host_file: 'inventory/host.yaml'
    #group_file: 'inventory/grupos.yaml'
    #defaults: 'inventory/defaults.yaml'


runner:
  plugin: threaded
  options: 
    num_workers: 2     172.16.111.61